# Generated by Django 5.2 on 2025-09-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='number_of_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='followers',
            name='number_of_following',
            field=models.IntegerField(default=0),
        ),
    ]
